name: Cypress Tests CI
on:
  pull_request:
  workflow_dispatch:

env:
  BACKEND_URL: ${{ secrets.TEST_BACKEND_URL }}

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # This fetches the repository's code and places it in the working directory of the workflow runner.

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      #  This step sets the worker up so that it can use node

      - name: Build application docker image
        run: docker build -t next-accelerator .
      # This builds the docker images

      - name: Run docker images
        run: docker compose up -d
        # This runs the docker images in detached mode

      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          wait-on: http://localhost:3000/api/health
          wait-on-timeout: 120
          command: npm run cy:run:ct