
name: lint-and-prettier  
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      # This fetches the repository's code and places it in the working directory of the workflow runner.
      
      
  
