
name: lint-and-prettier  
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      # This fetches the repository's code and places it in the working directory of the workflow runner.
      
      - name: Use Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
          
      - name: Install dependencies
        run: |
          npm install --silent \
          eslint \
          eslint-config-next \
          eslint-config-prettier \
          eslint-plugin-storybook \
          prettier \
          prettier-plugin-tailwindcss
          
      
