
name: Terraform Security Scan
on:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "config"
          hide-progress: true
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
