name: Scheduled Update

on:
  workflow_dispatch:

jobs:
  auto_branch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup python
        uses: actions/checkout@v4
        
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
