name: Scheduled Update

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup python
        uses: actions/checkout@v4
      # This fetches the repository's code and places it in the working directory of the workflow runner.
      
      - name: Upgrade pip and install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # This upgrades pip and then installs the requirements required for a project

      # Next would be a step to run the required python scripts but this wasn't added here to make it more reuseable
