# This workflow will create a branch for an issue if the new-branch label is present

name: Create Branch

# Controls when the workflow will run
on:
  # Triggers the workflow when a new issue is opened
  issues: 
    types: 
      - opened

jobs:
  # This workflow contains a single job to create the branch 
  create-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
